#!/usr/bin/env bash
# Tab Resource Monitor - one-command native-host installer (macOS / Linux).
#
# GENERATED by build-bootstrap.js — do not edit by hand.
#
# Installs the local helper that gives the extension real OS CPU/RAM and
# cross-window/profile tabs. Run it directly:
#
#   curl -fsSL https://raw.githubusercontent.com/yuriiluchyshyn/tab-resource-monitor/main/bootstrap.sh | bash
#
# Everything is self-contained (host.js is embedded below). No repo checkout,
# no npm, no arguments. Node.js is the only requirement.

set -u

HOST_NAME="com.billing.tabmonitor"
EXT_ID="hglmoipmbnckikkkaoppfpogcpbjjnnn"
APP_DIR="${TRM_HOME:-$HOME/.tab-resource-monitor}"

echo "Tab Resource Monitor - installing native helper"
echo "  location: $APP_DIR"

# --- Node.js required (the host is a Node script) ---------------------------
NODE_BIN="$(command -v node || true)"
if [ -z "$NODE_BIN" ]; then
  for c in /opt/homebrew/bin/node /usr/local/bin/node /usr/bin/node; do
    [ -x "$c" ] && NODE_BIN="$c" && break
  done
fi
if [ -z "$NODE_BIN" ]; then
  echo "error: Node.js not found. Install it from https://nodejs.org and re-run."
  exit 1
fi
echo "  node: $NODE_BIN"

# --- Write the host + launcher ----------------------------------------------
mkdir -p "$APP_DIR"

cat > "$APP_DIR/host.js" <<'TRM_HOST_EOF'
#!/usr/bin/env node
// Tab Resource Monitor - native messaging host
//
// A tiny local helper that Chrome launches (via chrome.runtime.connectNative)
// and talks to over stdin/stdout using Chrome's native-messaging framing
// (4-byte little-endian length prefix + UTF-8 JSON body).
//
// It answers two kinds of requests from the extension:
//
//   { id, cmd: "sample", debugPort?: number }
//       -> real OS numbers the extension can't get on its own:
//          - system CPU% and memory (total / used / free), from the OS
//          - every Chrome/Chromium process with real CPU% and RSS memory,
//            categorised (browser / gpu / renderer / utility / extension …)
//          - Chrome's TOTAL cpu% and memory (matches Activity Monitor)
//          - a per-OS-pid map so the extension can join real memory/CPU onto
//            individual tabs when chrome.processes exposes osProcessId
//          - (optional) every page target across ALL windows AND profiles via
//            the DevTools Protocol /json endpoint, when Chrome was started with
//            --remote-debugging-port=<debugPort>
//
//   { id, cmd: "closeTarget", debugPort, targetId }
//       -> close a tab by CDP target id (works even for other-profile tabs the
//          chrome.tabs API can't touch)
//
// Everything runs locally; nothing is sent anywhere. No external npm deps.

'use strict';

const os = require('os');
const http = require('http');
const { execFile } = require('child_process');

// ---- Native messaging framing ----------------------------------------------

// Chrome writes: [uint32 LE length][JSON bytes]. We accumulate stdin into a
// buffer and pull off complete messages.
let stdinBuf = Buffer.alloc(0);

process.stdin.on('data', (chunk) => {
  stdinBuf = Buffer.concat([stdinBuf, chunk]);
  // Drain as many complete frames as we have.
  while (stdinBuf.length >= 4) {
    const len = stdinBuf.readUInt32LE(0);
    if (stdinBuf.length < 4 + len) break; // wait for the rest
    const body = stdinBuf.slice(4, 4 + len);
    stdinBuf = stdinBuf.slice(4 + len);
    let msg = null;
    try {
      msg = JSON.parse(body.toString('utf8'));
    } catch (_) {
      continue; // skip a malformed frame
    }
    handleMessage(msg);
  }
});

// When Chrome disconnects it closes our stdin; exit cleanly.
process.stdin.on('end', () => process.exit(0));

function send(obj) {
  const json = Buffer.from(JSON.stringify(obj), 'utf8');
  const header = Buffer.alloc(4);
  header.writeUInt32LE(json.length, 0);
  try {
    process.stdout.write(Buffer.concat([header, json]));
  } catch (_) {
    /* stdout gone — Chrome closed the port */
  }
}

// ---- Request handling -------------------------------------------------------

async function handleMessage(msg) {
  if (!msg || typeof msg !== 'object') return;
  const id = msg.id;
  try {
    switch (msg.cmd) {
      case 'ping':
        send({ id, ok: true, pong: true, version: '1.0.1', platform: process.platform });
        return;
      case 'sample': {
        const data = await sample(msg.debugPort);
        send({ id, ok: true, ...data });
        return;
      }
      case 'closeTarget': {
        const ok = await cdpCloseTarget(msg.debugPort, msg.targetId);
        send({ id, ok });
        return;
      }
      default:
        send({ id, ok: false, error: 'unknown cmd: ' + msg.cmd });
    }
  } catch (e) {
    send({ id, ok: false, error: String((e && e.message) || e) });
  }
}

// ---- System CPU (delta between samples) ------------------------------------

// os.cpus() gives cumulative tick counters; overall CPU% is 1 - idleΔ/totalΔ.
let prevCpu = null;

function cpuTotals() {
  const cpus = os.cpus();
  let idle = 0;
  let total = 0;
  for (const c of cpus) {
    for (const k in c.times) total += c.times[k];
    idle += c.times.idle;
  }
  return { idle, total, cores: cpus.length };
}

function systemCpuPercent() {
  const cur = cpuTotals();
  let percent = null;
  if (prevCpu) {
    const idleDelta = cur.idle - prevCpu.idle;
    const totalDelta = cur.total - prevCpu.total;
    if (totalDelta > 0) percent = Math.max(0, Math.min(100, (1 - idleDelta / totalDelta) * 100));
  }
  prevCpu = cur;
  return { percent: percent == null ? null : Math.round(percent * 10) / 10, cores: cur.cores };
}

// ---- Process scan (ps) ------------------------------------------------------

function runPs() {
  // -A/-ax: all processes. Blank-named -o columns suppress the header so the
  // output is pure data. `command` (full argv) must be last since it contains
  // spaces. rss is in KB on macOS and Linux. pcpu is % (can exceed 100 across
  // cores). Works on macOS and Linux; on Windows we return [] (see caller).
  return new Promise((resolve) => {
    execFile(
      'ps',
      ['-axo', 'pid=,ppid=,pcpu=,rss=,command='],
      { maxBuffer: 8 * 1024 * 1024 },
      (err, stdout) => {
        if (err || !stdout) {
          resolve([]);
          return;
        }
        resolve(parsePs(stdout));
      }
    );
  });
}

function parsePs(stdout) {
  const rows = [];
  for (const line of stdout.split('\n')) {
    const s = line.trim();
    if (!s) continue;
    // pid ppid pcpu rss command...
    const m = s.match(/^(\d+)\s+(\d+)\s+([\d.]+)\s+(\d+)\s+(.*)$/);
    if (!m) continue;
    rows.push({
      pid: Number(m[1]),
      ppid: Number(m[2]),
      cpu: Number(m[3]),
      rssBytes: Number(m[4]) * 1024,
      command: m[5],
    });
  }
  return rows;
}

// Is this process one of Chrome's? Match the common executable names across
// Chrome / Chromium / Brave / Edge and their per-platform helper binaries.
const CHROME_EXE_RE =
  /(Google Chrome|Chromium|Brave Browser|Microsoft Edge|chrome\.exe|chrome$|chrome |\bchrome_crashpad|Google Chrome Helper|Chromium Helper|Brave Browser Helper|Microsoft Edge Helper)/i;

function isChrome(cmd) {
  return CHROME_EXE_RE.test(cmd);
}

// Map a Chrome process's argv to a friendly type + label.
function classify(cmd) {
  const typeMatch = cmd.match(/--type=([\w-]+)/);
  if (!typeMatch) {
    // No --type= → this is a main browser process (or an unrelated helper we
    // still counted as Chrome). The top-level browser has a Framework/app path.
    return { type: 'browser', label: 'Browser' };
  }
  const t = typeMatch[1];
  switch (t) {
    case 'renderer':
      return /--extension-process/.test(cmd)
        ? { type: 'extension', label: 'Extension' }
        : { type: 'renderer', label: 'Renderer (tab)' };
    case 'gpu-process':
      return { type: 'gpu', label: 'GPU process' };
    case 'utility': {
      const sub = cmd.match(/--utility-sub-type=([\w.-]+)/);
      const name = sub ? sub[1].split('.').pop() : 'Utility';
      return { type: 'utility', label: 'Utility · ' + name };
    }
    case 'zygote':
      return { type: 'zygote', label: 'Zygote' };
    case 'crashpad-handler':
      return { type: 'crashpad', label: 'Crashpad' };
    case 'broker':
      return { type: 'broker', label: 'Broker' };
    default:
      return { type: t, label: t };
  }
}

// ---- CDP (DevTools Protocol) over the /json HTTP endpoint -------------------

// GET http://127.0.0.1:<port><path>. Short timeout; resolves null on any error
// so a missing/closed debug port never blocks a sample.
function cdpGet(port, path) {
  return new Promise((resolve) => {
    if (!port) {
      resolve(null);
      return;
    }
    const req = http.get({ host: '127.0.0.1', port, path, timeout: 800 }, (res) => {
      let data = '';
      res.setEncoding('utf8');
      res.on('data', (d) => (data += d));
      res.on('end', () => resolve(data));
    });
    req.on('timeout', () => {
      req.destroy();
      resolve(null);
    });
    req.on('error', () => resolve(null));
  });
}

// Every page target across ALL windows and ALL profiles of the running Chrome.
async function cdpTargets(port) {
  const raw = await cdpGet(port, '/json/list');
  if (!raw) return null;
  let arr = null;
  try {
    arr = JSON.parse(raw);
  } catch (_) {
    return null;
  }
  if (!Array.isArray(arr)) return null;
  return arr
    .filter((t) => t && t.type === 'page' && !/^devtools:\/\//.test(t.url || ''))
    .map((t) => ({
      targetId: t.id,
      title: t.title || t.url || '(untitled)',
      url: t.url || '',
      faviconUrl: t.faviconUrl || '',
    }));
}

async function cdpCloseTarget(port, targetId) {
  if (!port || !targetId) return false;
  const raw = await cdpGet(port, '/json/close/' + encodeURIComponent(targetId));
  return raw != null; // endpoint returns "Target is closing" on success
}

// ---- Assemble a sample ------------------------------------------------------

async function sample(debugPort) {
  const [procs, targets] = await Promise.all([
    process.platform === 'win32' ? Promise.resolve([]) : runPs(),
    cdpTargets(debugPort),
  ]);

  const chrome = procs.filter((p) => isChrome(p.command));

  let chromeCpu = 0;
  let chromeRss = 0;
  const byPid = {}; // osPid -> { cpu, rssBytes, type }
  const processes = []; // non-renderer + renderer, for the UI breakdown

  for (const p of chrome) {
    const info = classify(p.command);
    chromeCpu += p.cpu;
    chromeRss += p.rssBytes;
    byPid[p.pid] = { cpu: Math.round(p.cpu * 10) / 10, rssBytes: p.rssBytes, type: info.type };
    processes.push({
      pid: p.pid,
      type: info.type,
      label: info.label,
      cpu: Math.round(p.cpu * 10) / 10,
      rssBytes: p.rssBytes,
    });
  }

  processes.sort((a, b) => b.rssBytes - a.rssBytes);

  const totalMem = os.totalmem();
  const freeMem = os.freemem();

  return {
    at: Date.now(),
    system: {
      cpuPercent: systemCpuPercent().percent,
      cpuCores: os.cpus().length,
      totalMemoryBytes: totalMem,
      freeMemoryBytes: freeMem,
      usedMemoryBytes: totalMem - freeMem,
      platform: process.platform,
    },
    chrome: {
      cpuPercent: Math.round(chromeCpu * 10) / 10,
      rssBytes: chromeRss,
      processCount: chrome.length,
      rendererCount: processes.filter((p) => p.type === 'renderer').length,
    },
    processes, // real per-process CPU/RSS, all channels
    byPid, // osPid -> {cpu,rssBytes,type} for tab joining (Dev channel)
    cdpAvailable: targets != null,
    targets: targets || [], // all tabs across windows+profiles (needs debug port)
  };
}

// Nothing else to do until Chrome sends a message.

TRM_HOST_EOF

cat > "$APP_DIR/run-host.sh" <<EOF
#!/usr/bin/env bash
exec "$NODE_BIN" "$APP_DIR/host.js"
EOF
chmod +x "$APP_DIR/run-host.sh"

# --- Register the manifest for every installed Chromium browser -------------
OS="$(uname -s)"
if [ "$OS" = "Darwin" ]; then
  BASES=(
    "$HOME/Library/Application Support/Google/Chrome"
    "$HOME/Library/Application Support/Google/Chrome Beta"
    "$HOME/Library/Application Support/Google/Chrome Dev"
    "$HOME/Library/Application Support/Google/Chrome Canary"
    "$HOME/Library/Application Support/Chromium"
    "$HOME/Library/Application Support/BraveSoftware/Brave-Browser"
    "$HOME/Library/Application Support/Microsoft Edge"
  )
else
  BASES=(
    "$HOME/.config/google-chrome"
    "$HOME/.config/google-chrome-beta"
    "$HOME/.config/google-chrome-unstable"
    "$HOME/.config/chromium"
    "$HOME/.config/BraveSoftware/Brave-Browser"
    "$HOME/.config/microsoft-edge"
  )
fi

read -r -d '' MANIFEST <<EOF || true
{
  "name": "$HOST_NAME",
  "description": "Tab Resource Monitor native host",
  "path": "$APP_DIR/run-host.sh",
  "type": "stdio",
  "allowed_origins": ["chrome-extension://$EXT_ID/"]
}
EOF

COUNT=0
for BASE in "${BASES[@]}"; do
  if [ -d "$BASE" ]; then
    DEST="$BASE/NativeMessagingHosts"
    mkdir -p "$DEST"
    printf '%s\n' "$MANIFEST" > "$DEST/$HOST_NAME.json"
    echo "  registered: $DEST/$HOST_NAME.json"
    COUNT=$((COUNT+1))
  fi
done

if [ "$COUNT" -eq 0 ]; then
  echo "warning: no Chromium-based browser profile found; nothing registered."
  echo "         (looked under the standard Chrome/Chromium/Brave/Edge locations)"
fi

echo
echo "Done. Open Tab Resource Monitor — the status line should read 'native: on'."
echo "(In the setup page, just press Re-check.)"
